version: '3'
services:
  #my-app:
  #image: myapplication
  #ports:
  # - 3000:3000
  mongodb:
    image: ${MY_MONGO_IMAGE}
    ports:
      - ${MY_MONGO_DB_HOST_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MY_ADMIN_ID}
      - MONGO_INITDB_ROOT_PASSWORD=${MY_ADMIN_PASSWORD}
    volumes:
      - ${MY_HOST_MONGO_DB_VOLUME}:/data/db
  mongo-express:
    image: ${MY_MONGO_EXPRESS_IMAGE}
    restart: ${MY_RESTART_MODE} # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - ${MY_MONGO_EXPRESS_HOST_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MY_ADMIN_ID}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MY_ADMIN_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MY_MONGODB_SERVER_NAME}
